name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # Runs every day at 8 hours

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # SHOW_PROJECTS: "False"
          # SHOW_PROFILE_VIEWS: "False"
          # SHOW_DAYS_OF_WEEK: "False"
          # SHOW_TIMEZONE: "False"
          # SHOW_LINES_OF_CODE: "False"
  
          INPUT_SHOW_TIMEZONE: True
          INPUT_SHOW_PROJECTS: True
          INPUT_SHOW_EDITORS: True
          INPUT_SHOW_OS: True
          INPUT_SHOW_LANGUAGE: True
          INPUT_SYMBOL_VERSION: 1
          INPUT_SHOW_LINES_OF_CODE: True
          INPUT_SHOW_LOC_CHART: True
          INPUT_SHOW_PROFILE_VIEWS: True
          INPUT_SHOW_TOTAL_CODE_TIME: True
          INPUT_SHOW_SHORT_INFO: True
          INPUT_SHOW_COMMIT: True
          INPUT_SHOW_DAYS_OF_WEEK: True
          INPUT_SHOW_LANGUAGE_PER_REPO: True
          INPUT_SHOW_UPDATED_DATE: True
          INPUT_COMMIT_BY_ME: True

