name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */7 * *"  # каждые 3 дня

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LINES_OF_CODE: "False"

